dotnet/SampleWeb/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SampleWeb.Pages {
    [ResponseCache (Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty (RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel (ILogger<ErrorModel> logger) {
            _logger = logger;
        }

        public void OnGet () {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

dotnet/SampleWeb/Pages/Index.cshtml.cs
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using Azure;
using Microsoft.Azure.Cosmos;
using Microsoft.AspNetCore.Mvc;

namespace SampleWeb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly string storageAddress = Environment.GetEnvironmentVariable("CONTENT_STORAGE");
        private readonly string storageContainerName = "testcontainer";
        private readonly string storageBlobName = "storagetest.txt";

        private readonly string cosmosEndpoint = Environment.GetEnvironmentVariable("COSMOS_ENDPOINT");
        private readonly string cosmosDatabaseName = "testdb";
        private readonly string cosmosContainerName = "cosmostest";

        private BlobServiceClient blobServiceClient;
        private BlobContainerClient blobContainerClient;
        private BlobClient blobClient;

        private CosmosClient cosmosClient;
        private Database cosmosDatabase;
        private Container cosmosContainer;

        // The log to show in the web page
        public string LogMessage { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            string domainName = Environment.GetEnvironmentVariable("WEBSITE_HOSTNAME");
            ViewData["Host"] = domainName;
            if (string.IsNullOrEmpty(domainName))
            {
                ViewData["Site"] = "Sample Container";
                ViewData["Host"] = "local or unknown";
            }
            else if (domainName.ToLower().Contains("msha"))
            {
                ViewData["Site"] = "Dedicated MSHA";
            }
            else if (domainName.ToLower().Contains("cds"))
            {
                ViewData["Site"] = "Dedicated CDS";
            }
            else
            {
                ViewData["Site"] = "Sample Container Web";
            }

            string sku = Environment.GetEnvironmentVariable("ENVIRONMENT_VERSION");

            if (string.IsNullOrEmpty(sku))
            {
                ViewData["Sku"] = "Unknown";
            }
            else
            {
                ViewData["Sku"] = sku;
            }
        }

        public async Task<IActionResult> OnGetStorageAsync()
        {
            // ' storage blob data contributor' is required before using MSI
            try
            {
                //blobServiceClient = new BlobServiceClient(
                //    new Uri(storageAddress),
                //    new ManagedIdentityCredential("6f60f59c-ca19-4715-a853-b822e9b97946")
                //);

                DefaultAzureCredential defaultAzureCredential = new DefaultAzureCredential();
                blobServiceClient = new BlobServiceClient(
                    new Uri(storageAddress),
                    defaultAzureCredential
                    );

                // Create blobContainerClient if not exists
                blobContainerClient = blobServiceClient.GetBlobContainerClient(storageContainerName);
                if (!await blobContainerClient.ExistsAsync())
                {
                    blobContainerClient = await blobServiceClient.CreateBlobContainerAsync(storageContainerName);
                }

                // Create BlobClient if not exists
                blobClient = blobContainerClient.GetBlobClient(storageBlobName);
                if (!await blobClient.ExistsAsync())
                {
                    await blobClient.UploadAsync(new MemoryStream());
                }

                // Write log to blob
                string log = $"[{DateTime.Now}] This is a log message from {ViewData["Site"]}.\n";
                await blobClient.UploadAsync(BinaryData.FromString(log), overwrite: true);

                // Read log from blob
                using (var stream = new MemoryStream())
                {
                    await blobClient.DownloadToAsync(stream);
                    LogMessage = System.Text.Encoding.UTF8.GetString(stream.ToArray());
                }
            }
            catch (Exception ex)
            {
                LogMessage = "Sorry, something went wrong. Please try again later.\n";
                LogMessage += ex.Message;
            }
            return Content(LogMessage);
        }

        public async Task<IActionResult> OnGetCosmosAsync()
        {
            try
            {
                DefaultAzureCredential defaultAzureCredential = new DefaultAzureCredential();
                cosmosClient = new CosmosClient(
                    cosmosEndpoint,
                    defaultAzureCredential
                );

                // Create a database asynchronously if it doesn't already exist
                cosmosDatabase = await cosmosClient.CreateDatabaseIfNotExistsAsync(
                    id: cosmosDatabaseName
                );

                // Create a container asynchronously if it doesn't already exist
                cosmosContainer = await cosmosDatabase.CreateContainerIfNotExistsAsync(
                    id: cosmosContainerName,
                    partitionKeyPath: "/Category",
                    throughput: 400
                );

                // Generate a random product Id
                string productId = "test";

                // Create an item
                Log tempLog = new Log
                {
                    id = productId,
                    Category = cosmosEndpoint,
                    Date = $"[{DateTime.Now}] This is a log message from {Environment.GetEnvironmentVariable("WEBSITE_HOSTNAME")}\n."
                };

                // Insert to cosmosContainer
                await cosmosContainer.UpsertItemAsync<Log>(tempLog);

                // Read from cosmosContainer
                Log result = await cosmosContainer.ReadItemAsync<Log>(productId, new PartitionKey(tempLog.Category));

                LogMessage = $"Created and read a new log: {result.Category}, {result.Date}\n";
            }
            catch (Exception ex)
            {
                LogMessage = "Sorry, something went wrong. Please try again later.\n";
                LogMessage += ex.Message;
            }
            return Content(LogMessage);
        }
    }

    public class Log
    {
        public string id { get; set; }
        public string Category { get; set; }
        public string Date { get; set; }
    }
}

dotnet/SampleWeb/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SampleWeb.Pages {
    public class PrivacyModel : PageModel {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel (ILogger<PrivacyModel> logger) {
            _logger = logger;
        }

        public void OnGet () {
        }
    }
}

dotnet/SampleWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-left">
    <h1 class="display-4">@ViewData["Site"]</h1>
    <p>This is a demo site for @ViewData["Site"].</p>
    <p>Site host - @ViewData["Host"].</p>
    <p>Site sku - @ViewData["Sku"].</p>
    <div style="width:100%; text-align:right;">
        <button id="read-write-storage" asp-page-handler="Storage" style="margin: 10px auto; margin-right: 30px;">Test Content Storage</button>
        <button id="read-write-cosmos" asp-page-handler="Cosmos" style="margin: 10px auto;">Test Cosmos DB</button>
    </div>
    <div id="output-container" style="position: relative; width: 100%; height: 600px; margin: 0 auto; border: 1px solid black">
        <div id="log-message" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; text-align:left; display: none">
            <pre>@Model.LogMessage</pre>
        </div>
        <div id="loading-message" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; text-align:left; display: none">
            <p>Please wait, we are processing your request...</p>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Add event listeners to the buttons
    $("#read-write-storage").click(function () {
        // Hide the log message and show the loading message
        $("#log-message").hide();
        $("#loading-message").show();

        // Call the OnGetStorageAsync method
        $.get("/Index?handler=Storage", function (data) {
            // Update the log message and show it
            $("#log-message").text(data);
            $("#log-message").show();
            $("#loading-message").hide();
        });
    });

    $("#read-write-cosmos").click(function () {
        // Hide the log message and show the loading message
        $("#log-message").hide();
        $("#loading-message").show();

        // Call the OnGetCosmosAsync method
        $.get("/Index?handler=Cosmos", function (data) {
            // Update the log message and show it
            $("#log-message").text(data);
            $("#log-message").show();
            $("#loading-message").hide();
        });
    });
</script>

dotnet/SampleWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SampleWeb - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>